#!/bin/sh

# 2monitor: turn on or off second monitor if connected.

outputs="HDMI-1 DP-2"

case "$1" in "-h" | "--help")
        echo "usage: 2monitor [on|off]"
        exit 0
        ;;
esac

output=""
for out in $outputs; do
        if xrandr | grep -q "$out connected"; then
                output="$out"
                break
        fi
done

if [ -z "$output" ]; then
        echo "error: $outputs: none connected" >&2
        exit 1
fi

case "$1" in
"off")
        xrandr --output "$output" --off ;;
*)
        xrandr --output "$output" --auto --primary --pos 0x0 --output eDP-1 --pos 1920x640 ;;
esac
