#!/bin/sh

# cprsyncsizeonly: like cprsync but do not --archive and use --size-only to skip
#                  files that match in size (ignoring timestamps). useful when
#                  timestamps are not accurate.

rsync --recursive --size-only --partial --info=progress2 --human-readable --itemize-changes "$@"
