#!/bin/sh

# headphones: connect or disconnect bluetooth headphones.

set -e

case "$1" in
"-h" | "--help")
        echo "usage: headphones device [on|off]"
        exit 0
        ;;
"" | "on" | "off")
        echo "error: device not provided" >&2
        exit 1
        ;;
esac

device="$1"
op="$2"

case "$op" in
"off")
        bluetoothctl disconnect "$device"
        ;;
*)
        bluetoothctl connect "$device"
        ;;
esac

refreshbar
