#!/bin/sh

# maintenance: upgrade and backup system.

backupdir="/home/marco/backup/`hostname`"

set -e
set -x

sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get autoremove --purge
sudo apt-get clean

sudo fstrim -av

if ping -c 1 -W 1 "nas"; then
        rsync -aAXzvi \
              --progress \
              --numeric-ids \
              --exclude=mnt \
              --delete \
              --rsync-path="mkdir -p $backupdir && rsync" \
              -e ssh "$HOME" "nas:$backupdir"
fi
