#!/bin/sh

# play: select and play music with mpv

while true; do
        case "$1" in
        "-h" | "--help")
                echo "usage: play [-d|--directory | -s|--shuffle | -t|--time] [name]"
                exit 0
                ;;
        "-d" | "--directory")
                directory=1
                ;;
        "-s" | "--shuffle")
                shuffle=1
                ;;
        "-t" | "--time")
                time=1
                ;;
        *)
                break
                ;;
        esac

        shift
done

if [ "$shuffle" = "1" ] && [ -z "$directory$time$*" ]; then
        mpv --shuffle "$HOME/music"
        exit $?
fi

type="${directory:+-type d}"
sort="shuf"
if [ "$time" = "1" ]; then
        type="${type:--type f}"
        sort="sort --reverse"
fi

find "$HOME/music" -mindepth 1 -not -path '*/.*' $type -printf "%T+ %p\n" \
 | $sort \
 | cut --delimiter ' ' --fields 2- \
 | fzf --delimiter / --with-nth 5.. --print0 --select-1 ${*:+--query="$*"} \
 | xargs --null --no-run-if-empty mpv ${shuffle:+--shuffle}
