#!/bin/sh

# play: select and play music with mpv

while true; do
        case "$1" in
        "-h" | "--help")
                echo "usage: play [-d|--directory | -s|--shuffle] [name]"
                exit 0
                ;;
        "-d" | "--directory")
                directory=1
                ;;
        "-s" | "--shuffle")
                shuffle=1
                ;;
        *)
                break
                ;;
        esac

        shift
done

if [ "$shuffle" = "1" ] && [ -z "$directory$time$*" ]; then
        mpv --shuffle "$HOME/music"
        exit $?
fi

find "$HOME/music" -mindepth 1 -not -name '.*' ${directory:+-type d} \
 | shuf \
 | fzf --delimiter / --with-nth 5.. --print0 --select-1 ${*:+--query="$*"} \
 | xargs --null --no-run-if-empty mpv ${shuffle:+--shuffle}
