#!/bin/sh

# playurl: select and play urls with mpv.
#          urlsfile is a plain text file containing the urls list, it must be
#          the first argument of playurl (i recommend to create some aliases for
#          convenience, i have "radio" and "tv"). the url must be the last field
#          in the file, e.g:
#
#            Radio Los Santos       https://rockstar.com/rls.mp3
#            West Coast Classics    https://rockstar.com/wcc.mp3
#
#          tips:
#          - put your favorite url at the top of the list to play it first.
#          - https://radio.garden is a nice place to scrape radio urls.
#          - https://github.com/iptv-org/iptv is nice for tv urls.

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$2" = "-h" ] || [ "$2" = "--help" ]; then
        echo "usage: playurl urlsfile [-l|-s|-z] [name]"
        exit 0
fi

urlsfile="$1"
shift

case "$1" in
"-l")
        awk 'NF > 1 { NF-- } NF { print ++i, $0 }' "$urlsfile"
        exit 0
        ;;
"-s")
        urls="$(awk 'NF' "$urlsfile" | shuf)"
        ;;
"-z")
        urls="$(awk 'NF == 1 { printf "%s%s", $0, FS } NF' "$urlsfile" | fzf --with-nth=..-2)"
        ;;
*)
        urls="$(awk -v "name=$*" 'NF && index(tolower($0), tolower(name))' "$urlsfile")"
        ;;
esac

if [ -z "$urls" ]; then
        echo "error: no url to play" >&2
        exit 1
fi

echo "$urls" | awk 'NF > 1 { NF-- } { print ++i, $0 }'
echo "$urls" | awk '{ print $NF }' | mpv --playlist=-
