#!/bin/sh

# stockprice: fetch live stock prices from yahoo finance

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        echo "usage: stockprice [symbol...]"
        exit 0
fi

agent="Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/116.0"

while [ $# -gt 0 ]; do
        symbol="$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')"
        shift

        curl --silent --fail --location "https://finance.yahoo.com/quote/$symbol" -H "User-Agent: $agent" \
         | xmllint --html --xpath "//*[@data-symbol=\"$symbol\" and @data-field=\"regularMarketPrice\"]/parent::div//text()" - 2> /dev/null \
         | awk -v "symbol=$symbol" 'BEGIN { printf("%s|%s", strftime("%Y-%m-%d %H:%M:%S"), symbol) } NF { printf("|%s", $0) } END { printf("\n") }' \
         &

done | sort | column --table --separator '|'

wait
