#!/bin/sh

# timer: countdown timer. spawns an alert window when time is up.

case "$1" in "-h" | "--help")
        echo "usage: timer minutes [tag...]"
        exit 0
        ;;
esac

[ "$1" -eq "$1" ] 2> /dev/null  # fails if $1 is not a number
if [ "$?" -ne 0 ] || [ "$1" -lt 0 ]; then
        echo "error: \"$1\": invalid number of minutes" >&2
        exit 1
fi

now="`date +%s`"
end="$(( $now + $1 * 60 ))"
while [ "$now" -lt "$end" ]; do
        rem="$(( $end - $now ))"
        printf "\r%02d:%02d:%02d" "$(( $rem/60/60 ))" "$(( $rem/60%60 ))" "$(( $rem%60 ))"
        sleep 1
        now="$(( $now + 1 ))"
done
echo

msg="timer $*
done!"
gxmessage -bg red -fg white -center -font "monospace 50" -default okay -title "$msg" "$msg"
