#!/bin/sh

# web: search or open things in the web browser from command line.

browser="firefox"
homepage="about:home"
defaultengine="https://www.google.com/search?q="

case "$1" in
"-h" | "--help")
        echo "usage: web [-p|--private] [a|g|gpt|m|r|s|t|w|wa|y] [search query...|url|file]"
        exit 0
        ;;
"-p" | "--private")
        browser="$browser --private-window"
        shift
        ;;
esac

case "$1" in
"a")
        baseurl="https://www.amazon.it/s/?field-keywords=" ;;
"g")
        baseurl="https://www.google.com/search?q=" ;;
"gpt")
        baseurl="https://chat.openai.com/" ;;
"m")
        baseurl="https://www.google.com/maps?q=" ;;
"r")
        baseurl="https://old.reddit.com/r/" ;;
"s")
        baseurl="https://www.google.com/search?q=site:stackoverflow.com+" ;;
"t")
        baseurl="https://web.telegram.org/" ;;
"w")
        baseurl="https://en.wikipedia.org/w/index.php?title=Special:Search&search=" ;;
"wa")
        baseurl="https://web.whatsapp.com/" ;;
"y")
        baseurl="https://www.youtube.com/results?search_query=" ;;
*)
        baseurl="" ;;
esac

if [ -n "$baseurl" ]; then
        shift
fi

IFS='+'
query="$*"
IFS=' '

if [ -z "$baseurl" ] && [ -z "$query" ]; then
        baseurl="$homepage"

elif [ -n "$baseurl" ] && [ -z "$query" ]; then
        baseurl="$(echo "$baseurl" | cut -d '/' -f 1-3)"

elif [ -z "$baseurl" ] && [ -n "$query" ]; then
        baseurl="$defaultengine"
        if [ -f "$query" ] || [ -d "$query" ]; then
                query="file://$(readlink -f "$query")"
        fi
        case "$query" in "http://"* | "https://"* | "file://"* )
                baseurl="" ;;
        esac
fi

cd "$HOME" # don't keep current directory busy by the browser

$browser "$baseurl$query" > /dev/null 2>&1 &
