#!/bin/sh

# ytsearch: search and select youtube video links (no api).
#           (many thanks to https://github.com/pystardust/ytfzf)

case "$1" in "-h" | "--help")
        echo "usage: ytsearch query..."
        exit 0
esac

curl -s -G "https://www.youtube.com/results" --data-urlencode "search_query=$*" \
 | tr -d '\n' \
 | sed -e 's#^.*var \+ytInitialData *=##' -e 's#;</script>.*##' \
 | jq -r '..
    | .videoRenderer?
    | select(.)
    | [.title.runs[0].text[:80], (.lengthText.simpleText//"N/A"), (.shortViewCountText.simpleText//"N/A"), (.publishedTimeText.simpleText//"N/A"), .longBylineText.runs[0].text, .videoId]
    | @tsv' \
 | column -s "$(printf '\t')" -t \
 | fzf --with-nth=..-2 \
 | awk '{ print "https://www.youtube.com/watch?v="$NF }'
