#!/bin/sh

# yxrss: extract rss feed url of youtube channels.

case "$1" in "-h" | "--help")
        echo "usage: yxrss [video-or-channel-url...]"
        exit 0
        ;;
esac

for url in "$@"; do
        channelid="$(curl --silent --location "$url" \
         | xmllint --html --xpath "string(//meta[@itemprop='channelId']/@content)" - 2> /dev/null)"

        if [ -z "$channelid" ]; then
                printf "error: unable to extract channel id from %s\n" "$url" >&2
                continue
        fi

        printf "https://youtube.com/feeds/videos.xml?channel_id=%s\n" "$channelid"
done
